version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/notif_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notif.rule=Host(`notif.emotives.net`)"
      - "traefik.http.routers.notif.tls=true"
      - "traefik.http.routers.notif.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - notif

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik