version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/notif/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres@postgres_db:5432/notif_db
      VERIFICATION_URL: http://uacl/authorize
      HOST: 0.0.0.0
      PORT: 80
      AUTHORIZATION_SECRET: devSecret
      ALLOWED_ORIGINS: http://localhost
    volumes:
      - ../../:/app
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notif.rule=Host(`notif.localhost`)"
      - "traefik.http.routers.notif.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - notif

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
