version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/notif_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DATABASE_URL: postgres://postgres@postgres_db:5432/notif_db
      VERIFICATION_URL: http://uacl/authorize
      HOST: 0.0.0.0
      PORT: 80
      AUTHORIZATION_SECRET: "${AUTHORIZATION_SECRET:?}"
      EMAIL_FROM: emotives.acc@gmail.com
      EMAIL_PASSWORD: "${GMAIL_PASSWORD:-}"
      EMAIL_LEVEL: PROD
      ALLOWED_ORIGINS: https://emotives.net,https://www.emotives.net
    logging:
      driver: syslog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notif.rule=Host(`notif.emotives.net`)"
      - "traefik.http.routers.notif.tls=true"
      - "traefik.http.routers.notif.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - notif

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik